### PR TITLE
Fix wrong position and caption to lightbox image

### PR DESCRIPTION
**Pull request by vxcamiloxv**
This PR will fix the center position (currently not totally center in screen) and the wrong image caption, also adds some styles for the caption, the lightbox should be shown the content as a caption? for me has more logic show the title (displayName) of the note because the content could be too long, this PR also set a `max-heigth` for preventing too long contents.

closes: #639 #640

**Some screenshots:**

### Current error
error

### The Change

change

### CODE REVIEW

**Comment by vxcamiloxv** [comment]
@strugee  I think yes, but I don't remember, so I downloaded again and restore de 644 permission for that files.

**Comment by strugee** [comment]
So I tried this out locally and the caption seems kinda offset?

screen shot 2018-03-29 at 11 20 31 pm

**Comment by vxcamiloxv** [comment]
@strugee  Did you test with the last version? did you build the templates? for me works fine.  

OS: Parabola Gnu/Linux
Browser: Iceweasel 59 (Firefox) and Falkon 3.0 (Webkit)

screenshot-2018-04-02_12-10-10
screenshot-2018-04-02_12-13-30

**Comment by strugee** [comment]
That's a great question; it's very possible I didn't build the templates. I'll try again.

**Comment by strugee** [comment]
@vxcamiloxv wow, can't believe this dropped off my radar _again_. Anyway I tried this locally and it looks great. Thanks for your patience.

**Pull request merged**
