### PR TITLE
Styles js license page according to pump interface

### PR DESCRIPTION
**Pull request by vxcamiloxv**

### CODE REVIEW

**Comment by strugee** [comment]
Generally this LGTM; can you post a screenshot?

Also can you change "js" to "JS" in your commit message? Thank you!

**Comment by vxcamiloxv** [comment]
Update comment

JS Page

**Comment by strugee** [comment]
Thank you!

**Comment by strugee** [comment]
And sorry it's taking me so long to review your PRs - hopefully I'll get to them soon :)

**Comment by vxcamiloxv** [comment]
;)

**Pull request merged**
