### PR TITLE
Replaced bro image with picture of community members.

### PR DESCRIPTION
**Pull request by Aeva**
The photograph is cc-by-sa, but I have waived it as CC0 to make things
simple for including it in pump-io.  The photo is of the MediaGoblin
OPW volunteers (participants and a mentor) giving Bassam Kurdali a
group-hug.  Jessica Tallon, seen on the left is currently adding
federation support via the pump api to MediaGoblin.

### CODE REVIEW

**Comment by Aeva** [comment]
:D

**Comment by paultag** [comment]
!

**Comment by strugee** [comment]
@Aeva @paultag <3

Meant to leave a comment explaining this but forgot. I'm not sure if this'll go in or not but I'd like to at least consider it. @Aeva can you rebase this on top of current `master`? While you're at it, can you remove the `.` from the commit message subject line and change "api" to "API"? Thanks!

**Comment by Aeva** [comment]
Changes have been made!

**Comment by vxcamiloxv** [comment]
close in favor of https://github.com/pump-io/pump.io/pull/1486

**Comment by strugee** [comment]
I wonder if we should ask Evan about changing the default in the next meeting, I don't have strong opinions and I'm wondering why he left these open

**Comment by Serkan-devel** [comment]
But is Evan still here? His site has been down for a while even though he was notified

**Comment by strugee** [comment]
He shows up for meetings.

**Pull request closed without merging**
