### PR TITLE
Simplify databank driver install instructions

### PR DESCRIPTION
**Pull request by grdryn**
Installing databank drivers as a normal dependency works fine, they don't
need to be installed inside databank module.

### CODE REVIEW

**Comment by strugee** [comment]
@grdryn if you want to rebase this PR on top of `master` I'd be interested in taking it. I'm not 100% sure this is true across all Node versions though, so we'd have to test it.

Or perhaps we should just move Databank driver install instructions to the ReadTheDocs project?

**Comment by grdryn** [comment]
@strugee sorry, I just saw this now. I'll rebase & then you can decide if it should be merged here or moved to the docs project. :)

**Comment by strugee** [comment]
@grdryn lovely, thank you. Not sure when the move will happen (if ever) so I'll merge this here.

Reviewing the module location algorithm, it seems to me that this will work across all Node versions. Did you test locally? If so LGTM

**Comment by grdryn** [comment]
@strugee sorry, I don't have mail notifications for this project at the moment, so I didn't see this until now.

I haven't tested this with all node versions, but I have tested it (over 3 years ago it seems). :) The [instructions in the wiki to install on OpenShift v2](https://github.com/pump-io/pump.io/wiki/OpenShift) depend on this working.

Another possibility here is that we could just add all the known/tested databank drivers as top level dependencies here in pump.io. This would mean that we could remove the (essentially mandatory) step altogether, and instead have an optional note for people that want to use their own driver. It would also give some control over versions of drivers that people use with this project (imagine if databank had a breaking API change and some drivers got updated and others didn't).

**Comment by strugee** [comment]
I don't think we're going to start shipping Databank drivers. Thanks for the PR, though.

Merging since AFAICT this works and you did some basic testing.

**Pull request merged**
