### PR TITLE
Single js file for jade templates and render without eval

### PR DESCRIPTION
**Pull request by vxcamiloxv**
For better client side performance is better all jade templates in a
single js file, this reduce http calls and no need eval (can be harmful).

This solution generate `templates.js` every server run, is better for
development because when you run `forever -w` or other similar tool and
makes changes in some .jade template generate the file after reboot.

Related: #1231

### CODE REVIEW

**Comment by strugee** [comment]
Heya! Thanks for contributing to pump.io!

Unfortunately, this adds pretty significant overhead to initial requests which significantly increases the time before initial content gets filled in - this is not great and is especially problematic since we doesn't do cache-busting and don't do a great job rendering initial HTML on the server-side. Note also that while `eval()` can be dangerous, it is safe in this context. I don't think the tradeoff is worth it, so I'm closing.

I'd still love to accept PRs to implement the original design described in #1231. Let me know if you want to discuss this further.

**Comment by vxcamiloxv** [comment]
For reduce  overhead can implement task with gulp or similar to minify the code or use async o prefetch html properties. in my opinion the initial design with .utml (also with mustache or similar) is more efficient, 

The current solution is not friendly for developments becase need run build in any change of template and build all templates in any change.

The inicial startup in more slow by seconds, buts the call in other pages is more fast, when a user start to navigate the in pages is more fast but current every page change is more slow, in a slow server or home server is better a one initial load and deduce request, I thinks is better use other framework with own template enginner like vue.js or ember.js

You can acepts solution for optimized this implementacion? using prefetch o similar?

**Comment by strugee** [comment]
> For reduce overhead can implement task with gulp or similar to minify the code or use async o prefetch html properties.

JS generated by Jade is already minified.

> The current solution is not friendly for developments becase need run build in any change of template and build all templates in any change.

Yes, this is something I'd like to improve upon. Jade has an option to watch for changes which will help.

> The inicial startup in more slow by seconds

Yep. Regrettably multiple seconds is unacceptable from a performance point of view.

> using prefetch o similar?

It sounds like you're suggesting prefetching each Jade file so the template is already available when users navigate to different pages? If so then yes, I would be happy to take patches implementing that. That's what's suggested in #1231.

**Comment by vxcamiloxv** [comment]
> JS generated by Jade is already minified

Is't true, jade output is't ['pretty'](https://github.com/pugjs/pug/blob/master/packages/pug/lib/index.js#L294) but not minified(Compressed), are diferents concepts, for minified you need tools like [uglifyJS](https://github.com/mishoo/UglifyJS2)

> Regrettably multiple seconds is unacceptable from a performance point of view.

In my test[1], the initial startup is very similar in two cases (relative to network) and in some tests the current solution is more slow, best frontEnd practices say: [Minimize Requests](https://jonsuh.com/blog/need-for-speed-2/#javascript)

In my last commit only compile necessary templates (-client) and the files size reduce to 290K and minified 172K, similar size to jquery lib, one js more is no big deal, not increment the initial startup and reduces the http request.

[1]
test brwoser

**Comment by strugee** [comment]
> Is't true, jade output is't 'pretty' but not minified(Compressed), are diferents concepts, for minified you need tools like uglifyJS

Hmm, I thought Jade minified stuff. It's not really documented; I filed pugjs/pug#2767 on this.

As for your test results, they're interesting. However I'm pretty suspicious of your first benchmark. There _must_ have been some external factor at play there... there is absolutely no way that adding 300K of JS reduced the time by 0.2 seconds. That's just not possible.

More broadly, though it seems that the performance problems with this aren't as bad as I originally thought, I'm still a no on this one. If we prefetch templates in advance that makes time waiting for a request-response cycle a non-issue (especially with cache-busting), which is by far the biggest reason to minimize requests. And keeping templates in separate files still has an initial startup advantage (though not as big as I thought) and means we can still reuse a lot of cached resources even if some of the templating changes across versions, etc. Whereas if we put all the templates in one big file, even if we changed a single line in an obscure page, that would invalidate 100% of the web UI caches.

**Comment by vxcamiloxv** [comment]
Yes, I agree, one line would invalidate caching and need get all templates.

**Comment by strugee** [comment]
Sounds like we're on the same page then.

**Comment by vxcamiloxv** [comment]
Yes, I work in this moment in CacheBust, But I'm still not convinced using eval :D

**Comment by strugee** [comment]
@vxcamiloxv the two main problems with `eval()` are performance and security. Performance is not an issue because we only `eval()` templates once and then cache the result, so it doesn't happen in any hot code paths or anything. The security issues with it are that if a user is able to get some text into an `eval()`'d string, they can perform an XSS attack, but this is also a non-issue because we're careful to only `eval()` templates sent by the server, which we trust. It's not possible for user input to get into this codepath.

**Comment by strugee** [comment]
Another problem with `eval()` is that it is commonly misused for certain things - see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Don%27t_use_eval_needlessly!. This also doesn't apply to us because we don't do any of those things.

**Comment by vxcamiloxv** [comment]
But is little ugly solution and unnecessary, eval is very slow and some templates are big, you have other options.
1. Inject js dynamically in the DOM
2. HTML Render in server side 
    - .render() always pass 'principalUser' for compile template, this information also live in server session and you can render in server and return the HTML

**Comment by strugee** [comment]
> But is little ugly solution and unnecessary, eval is very slow and some templates are big, you have other options.

`eval()` is not slow in this case. The main reason that `eval()` is slow is when people `eval()` the same code multiple times (which interferes with the JS engine's optimizer) or, even worse, change values interpolated into the `eval()`'d code ever-so-slightly, which makes optimization impossible because even though 95% of the code is the same, the engine is not able to optimize the entire thing due to that one little difference.

This doesn't apply in pump.io's case, because we never `eval()` the same string more than once and we don't interpolate values into the string. Once the template function has been loaded, it acts basically like a regular function and can be optimized as normal by the VM. The reason we never `eval()` the same string more than once is because we cache the function after it's `eval()`'d - in subsequent uses of that template, the function will be pulled from the cache. You can see this logic in action by examining the code surrounding the `eval()` calls.

Don't get me wrong, being suspicious of `eval()` is generally a Very Good Thing. It's just that in this case, it's perfectly legitimate.

> Inject js dynamically in the DOM

This incurs basically the same performance cost. With both DOM injection and `eval()`, you're incurring a performance hit for parse time, which is of course completely unavoidable. After that in both cases you get a completely normal JavaScript function object which is optimized normally by the VM.

In fact, I think doing it this way _may_ be even faster than doing it via DOM injection, because any call accessing the DOM is slow. This way you avoid that access. But I'm not 100% sure on that, so don't quote me.

Even if they were about the same speed I would still say stay with the current solution, because it works and we have better things to do.

> HTML Render in server side

This incurs an additional round-trip for every page change, while the current approach only incurs a round-trip for the first time a template is used in a session (and once #1204 lands will only incur a round-trip for the absolute first time a template is used, basically ever).

To be clear, when I talked about expanding the amount of HTML we render server-side in other issues, I wasn't proposing replacing any of the client-side logic with that. The reason we'd do that is because it opens up the possibility of us supporting JS being disabled, because I believe in progressive enhancement, because I believe in [js;dr][], and because it decreases the time to first paint on initial page loads (when a user directly visits a pump.io page). None of that has to do with the performance of navigation _within the app_ :)

 [js;dr]: http://tantek.com/2015/069/t1/js-dr-javascript-required-dead

**Comment by vxcamiloxv** [comment]
Good points, js;dr is very interesting, a good option for the future of the pump.io is have the two options, detect what is the better option to return, static for console browser, curl, wget and with JS for modern browser and can be enabled or disabled by browser extensions or by profile configuracion.

regards ;)

**Comment by strugee** [comment]
@vxcamiloxv actually there's no reason we wouldn't return static content for browsers with JS enabled (it'll improve perf, in fact). We'll do that always and single-page functionality in JS will basically become a [progressive enhancement][].

 [progressive enhancement]: https://en.wikipedia.org/wiki/Progressive_enhancement

**Comment by strugee** [comment]
@vxcamiloxv I wanted to come back to this to explicitly say, both for you and for those stumbling on this thread, that I would seriously encourage you to keep asking questions like this. Some of the responses I wrote above I had to look up in order to double-check that some assumptions I made were right, which is great for me as a programmer _and_ serves to help make sure the project is the best it can be. So don't take this as a reason to stop challenging my reasoning! I actually really appreciate it :)

**Comment by vxcamiloxv** [comment]
@strugee Great, That's the idea, stay curious and self-critical

**Pull request closed without merging**
